.TH "NEAT_PyGenetics.NEAT.Repository.DatabaseConnector.DatabaseConnector" 3 "Wed Apr 6 2016" "NEAT_PyGenetics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NEAT_PyGenetics.NEAT.Repository.DatabaseConnector.DatabaseConnector \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBget_collection\fP"
.br
.ti -1c
.RI "def \fBinsert_one\fP"
.br
.ti -1c
.RI "def \fBinsert_many\fP"
.br
.ti -1c
.RI "def \fBfind_one\fP"
.br
.ti -1c
.RI "def \fBfind_one_by_id\fP"
.br
.ti -1c
.RI "def \fBfind_many\fP"
.br
.ti -1c
.RI "def \fBupdate_one\fP"
.br
.ti -1c
.RI "def \fBupdate_many\fP"
.br
.ti -1c
.RI "def \fBremove_one\fP"
.br
.ti -1c
.RI "def \fBremove_many\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBresult_ids\fP"
.br
.ti -1c
.RI "\fBi\fP"
.br
.ti -1c
.RI "\fBresult\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file DatabaseConnector\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NEAT_PyGenetics from the source code\&.
