.TH "NEAT_PyGenetics.NEAT.Simulator.Simulator.Simulator" 3 "Wed Apr 6 2016" "NEAT_PyGenetics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NEAT_PyGenetics.NEAT.Simulator.Simulator.Simulator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBsimulate_genome\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBsimulation_genome\fP"
.br
.ti -1c
.RI "\fBinputs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file Simulator\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NEAT_PyGenetics from the source code\&.
