.TH "NEAT_PyGenetics.NEAT.GenomeStructures.SimulationStructure.SimulationNodes.CycleNode" 3 "Wed Apr 6 2016" "NEAT_PyGenetics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NEAT_PyGenetics.NEAT.GenomeStructures.SimulationStructure.SimulationNodes.CycleNode \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNEAT_PyGenetics\&.NEAT\&.GenomeStructures\&.SimulationStructure\&.SimulationNodes\&.Node\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBadd_cycle_successor\fP"
.br
.ti -1c
.RI "def \fBadd_cycle_successors\fP"
.br
.ti -1c
.RI "def \fBfire_cycles\fP (self)"
.br
.ti -1c
.RI "def \fBpreserve_memory\fP (self)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBcycle_successors\fP"
.br
.ti -1c
.RI "\fBcycle_weights\fP"
.br
.ti -1c
.RI "\fBmemory_value\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 100 of file SimulationNodes\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def NEAT_PyGenetics\&.NEAT\&.GenomeStructures\&.SimulationStructure\&.SimulationNodes\&.CycleNode\&.fire_cycles ( self,  None)"

.PP
.nf
Adds the last stored value multiplied with the specific weights to all
cycle closing successors.
Serves as some kind of short time memory. (Use to be determined)
:return:

.fi
.PP
 
.PP
Definition at line 157 of file SimulationNodes\&.py\&.
.SS "def NEAT_PyGenetics\&.NEAT\&.GenomeStructures\&.SimulationStructure\&.SimulationNodes\&.CycleNode\&.preserve_memory ( self,  None)"

.PP
.nf
Copies the current value into the memory_value.
:return:

.fi
.PP
 
.PP
Definition at line 169 of file SimulationNodes\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NEAT_PyGenetics from the source code\&.
