.TH "NEAT_PyGenetics.NEAT.Analyst.GenomeAnalyst.GenomeAnalyst" 3 "Wed Apr 6 2016" "NEAT_PyGenetics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NEAT_PyGenetics.NEAT.Analyst.GenomeAnalyst.GenomeAnalyst \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBanalyze\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBtopologically_sorted_nodes\fP"
.br
.ti -1c
.RI "\fBcycle_edges\fP"
.br
.ti -1c
.RI "\fBtopologically_sorted_cycle_nodes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file GenomeAnalyst\&.py\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def NEAT_PyGenetics\&.NEAT\&.Analyst\&.GenomeAnalyst\&.GenomeAnalyst\&.__init__ ( self)"

.PP
.nf
_node_visited:
  _node_visited[i] = 0 => node with id i was not visited yet
  _node_visited[i] = 1 => node with id i was visited
:return:

.fi
.PP
 
.PP
Definition at line 9 of file GenomeAnalyst\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NEAT_PyGenetics from the source code\&.
