.TH "NEAT_PyGenetics.NEAT.Networking.Server.NEATServer.QueueWorker" 3 "Wed Apr 6 2016" "NEAT_PyGenetics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NEAT_PyGenetics.NEAT.Networking.Server.NEATServer.QueueWorker \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Thread\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBrun\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsocket\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
A thread which operates on networking message queues
via JSONSocket in two different modes:

1. receive
The worker thread will accept JSONSocket connections,
receive dictionaries, creates command objects and inserts them
into the appropriate queue (in_queue)

2. send
The worker thread will wait for command objects to appear inside
the outgoing queue (out_queue), convert them to dictionaries
and send them to the client via a JSONSocket.

.fi
.PP
 
.PP
Definition at line 35 of file NEATServer\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NEAT_PyGenetics from the source code\&.
