.TH "NEAT_PyGenetics.NEAT.Decisions.DecisionMaker.DecisionMaker" 3 "Wed Apr 6 2016" "NEAT_PyGenetics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NEAT_PyGenetics.NEAT.Decisions.DecisionMaker.DecisionMaker \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, decision_making_parameters)"
.br
.ti -1c
.RI "def \fBadvance_time\fP (self)"
.br
.ti -1c
.RI "def \fBreset_time\fP (self)"
.br
.ti -1c
.RI "def \fBmutation_percentage\fP (self)"
.br
.ti -1c
.RI "def \fBinter_cluster_breeding_time\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file DecisionMaker\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NEAT_PyGenetics from the source code\&.
