.TH "NEAT_PyGenetics.NEAT.Networking.Commands.SetFitnessValuesCommand.SetFitnessValuesCommand" 3 "Wed Apr 6 2016" "NEAT_PyGenetics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NEAT_PyGenetics.NEAT.Networking.Commands.SetFitnessValuesCommand.SetFitnessValuesCommand \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits BaseCommand\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBset_fitness_values\fP"
.br
.ti -1c
.RI "def \fBset_fitness_value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file SetFitnessValuesCommand\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NEAT_PyGenetics from the source code\&.
