.TH "NEAT_PyGenetics.NEAT.Tests.NetworkingTests.Server.test_JSONSocket.TestJSONSocket" 3 "Wed Apr 6 2016" "NEAT_PyGenetics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NEAT_PyGenetics.NEAT.Tests.NetworkingTests.Server.test_JSONSocket.TestJSONSocket \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBtest_socket_alive\fP (self)"
.br
.ti -1c
.RI "def \fBtest_close_connection\fP (self)"
.br
.ti -1c
.RI "def \fBtest__receive_message\fP (self)"
.br
.ti -1c
.RI "def \fBtest__receive_message_size\fP (self)"
.br
.ti -1c
.RI "def \fBtest__send_message\fP (self)"
.br
.ti -1c
.RI "def \fBtest__serialize_message_size\fP (self)"
.br
.ti -1c
.RI "def \fBtest__serialize_dict\fP (self)"
.br
.ti -1c
.RI "def \fBtest__deserialize_dict\fP (self)"
.br
.ti -1c
.RI "def \fBtest__connect\fP (self)"
.br
.ti -1c
.RI "def \fBtest_send_dict\fP (self)"
.br
.ti -1c
.RI "def \fBtest_receive_dict\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 4 of file test_JSONSocket\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NEAT_PyGenetics from the source code\&.
