.TH "NEAT_PyGenetics.NEAT.Repository.Transformator.Transformator" 3 "Wed Apr 6 2016" "NEAT_PyGenetics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NEAT_PyGenetics.NEAT.Repository.Transformator.Transformator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBencode_AnalysisResult\fP"
.br
.ti -1c
.RI "def \fBdecode_AnalysisResult\fP"
.br
.ti -1c
.RI "def \fBencode_StorageGenome\fP"
.br
.ti -1c
.RI "def \fBdecode_StorageGenome\fP"
.br
.ti -1c
.RI "def \fBencode_Cluster\fP"
.br
.ti -1c
.RI "def \fBdecode_Cluster\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file Transformator\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NEAT_PyGenetics from the source code\&.
