.TH "NEAT_PyGenetics.NEAT.Tests.Decisions.test_decisionMaker.TestDecisionMaker" 3 "Wed Apr 6 2016" "NEAT_PyGenetics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NEAT_PyGenetics.NEAT.Tests.Decisions.test_decisionMaker.TestDecisionMaker \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetUp\fP (self)"
.br
.ti -1c
.RI "def \fBtest_advance_time\fP (self)"
.br
.ti -1c
.RI "def \fBtest_reset_time\fP (self)"
.br
.ti -1c
.RI "def \fBtest_mutation_percentage\fP (self)"
.br
.ti -1c
.RI "def \fBtest_inter_cluster_breeding_time\fP (self)"
.br
.ti -1c
.RI "def \fBtest__cutoff_function\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBselection_parameter\fP"
.br
.ti -1c
.RI "\fBdecision_maker\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 7 of file test_decisionMaker\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NEAT_PyGenetics from the source code\&.
