.TH "NEAT_PyGenetics.NEAT.Tests.LogginTests.test_logger.TestLogger" 3 "Wed Apr 6 2016" "NEAT_PyGenetics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NEAT_PyGenetics.NEAT.Tests.LogginTests.test_logger.TestLogger \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetUp\fP (self)"
.br
.ti -1c
.RI "def \fBtest_log_levels\fP (self)"
.br
.ti -1c
.RI "def \fBtest_log_labels\fP (self)"
.br
.ti -1c
.RI "def \fBtest_lookup_log_level\fP (self)"
.br
.ti -1c
.RI "def \fBtest_lookup_log_level_label\fP (self)"
.br
.ti -1c
.RI "def \fBtest_lookup_log_file\fP (self)"
.br
.ti -1c
.RI "def \fBtest_get_timestamp\fP (self)"
.br
.ti -1c
.RI "def \fBtest_log\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBlogger\fP"
.br
.ti -1c
.RI "\fBlog_levels\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 11 of file test_logger\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NEAT_PyGenetics from the source code\&.
