.TH "NEAT_PyGenetics.NEAT.Networking.Commands.GetBlockCommand.GetBlockCommand" 3 "Wed Apr 6 2016" "NEAT_PyGenetics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NEAT_PyGenetics.NEAT.Networking.Commands.GetBlockCommand.GetBlockCommand \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits BaseCommand\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBset_block_id\fP"
.br
.ti -1c
.RI "def \fBget_block_id\fP (self)"
.br
.ti -1c
.RI "def \fBget_block\fP (self)"
.br
.ti -1c
.RI "def \fBget_block_size\fP (self)"
.br
.ti -1c
.RI "def \fBget_resulting_block_id\fP (self)"
.br
.ti -1c
.RI "def \fBget_next_block_id\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file GetBlockCommand\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NEAT_PyGenetics from the source code\&.
