.TH "NEAT_PyGenetics.NEAT.ErrorHandling.Exceptions.StartupCheckException.StartupCheckException" 3 "Wed Apr 6 2016" "NEAT_PyGenetics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NEAT_PyGenetics.NEAT.ErrorHandling.Exceptions.StartupCheckException.StartupCheckException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, message='', errors=None)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 1 of file StartupCheckException\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NEAT_PyGenetics from the source code\&.
