.TH "NEAT_PyGenetics.NEAT.Repository.GenomeRepository.GenomeRepository" 3 "Wed Apr 6 2016" "NEAT_PyGenetics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NEAT_PyGenetics.NEAT.Repository.GenomeRepository.GenomeRepository \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP"
.br
.ti -1c
.RI "def \fBget_current_population\fP (self)"
.br
.ti -1c
.RI "def \fBget_genome_by_id\fP"
.br
.ti -1c
.RI "def \fBget_genomes_in_cluster\fP"
.br
.ti -1c
.RI "def \fBinsert_genome\fP"
.br
.ti -1c
.RI "def \fBinsert_genomes\fP"
.br
.ti -1c
.RI "def \fBupdate_genome\fP"
.br
.ti -1c
.RI "def \fBupdate_genomes\fP"
.br
.ti -1c
.RI "def \fBdisable_genome\fP"
.br
.ti -1c
.RI "def \fBdisable_genomes\fP"
.br
.ti -1c
.RI "def \fBupdate_genome_fitness\fP"
.br
.ti -1c
.RI "def \fBupdate_genomes_fitness\fP"
.br
.ti -1c
.RI "def \fBupdate_genome_cluster\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBget_new_genome\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBgenome\fP"
.br
.ti -1c
.RI "\fBcluster\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 8 of file GenomeRepository\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def NEAT_PyGenetics\&.NEAT\&.Repository\&.GenomeRepository\&.GenomeRepository\&.get_current_population ( self,  Iterable,  StorageGenome)"

.PP
.nf
:return: Iterable[StorageGenomes] which are alive

.fi
.PP
 
.PP
Definition at line 26 of file GenomeRepository\&.py\&.
.SS "def NEAT_PyGenetics\&.NEAT\&.Repository\&.GenomeRepository\&.GenomeRepository\&.get_new_genome ( StorageGenome)\fC [static]\fP"

.PP
.nf
:return: StorageGenome new StorageGenome

.fi
.PP
 
.PP
Definition at line 18 of file GenomeRepository\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NEAT_PyGenetics from the source code\&.
