.TH "NEAT_PyGenetics.NEAT.Logging.Logger.Logger" 3 "Wed Apr 6 2016" "NEAT_PyGenetics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NEAT_PyGenetics.NEAT.Logging.Logger.Logger \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, logging_path)"
.br
.ti -1c
.RI "def \fBlog\fP"
.br
.ti -1c
.RI "def \fBopen_log\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBlog_levels\fP ()"
.br
.ti -1c
.RI "def \fBlog_labels\fP ()"
.br
.ti -1c
.RI "def \fBlookup_log_level\fP"
.br
.ti -1c
.RI "def \fBlookup_log_level_label\fP"
.br
.ti -1c
.RI "def \fBlookup_log_file\fP"
.br
.ti -1c
.RI "def \fBget_timestamp\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Logs messages to different files, based
on the reported log level.

Log levels:

0 - Debug
1 - Info
2 - Significant Info
3 - Warning
4 - Significant Warning
5 - Error
6 - Significant Error

.fi
.PP
 
.PP
Definition at line 4 of file Logger\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NEAT_PyGenetics from the source code\&.
