.TH "NEAT_PyGenetics.NEAT.Analyst.Cluster.Cluster" 3 "Wed Apr 6 2016" "NEAT_PyGenetics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NEAT_PyGenetics.NEAT.Analyst.Cluster.Cluster \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fB__eq__\fP"
.br
.ti -1c
.RI "def \fBcluster_id\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBrepresentative\fP"
.br
.ti -1c
.RI "\fBfitness\fP"
.br
.ti -1c
.RI "\fBoffspring\fP"
.br
.ti -1c
.RI "\fBalive\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Object used to represent a single cluster as stored
in the database.

Attributes:
    cluster_id (_id):
        The Cluster's ID, unique
    representative:
        The ID of the representative StorageGenome.
        All genomes in the cluster are topologically similar
        to it's representative genome.
    fitness:
        The cluster's fitness value.
        This is calculated from the fitness values of the
        contained genomes by a shared fitness approach.
    offspring:
        The amount of offspring that will be generated based
        on genomes from this clusters during the next generation.
    alive:
        Whether the cluster is alive, i.e. if there are any
        genomes in the current population which belong to this
        cluster.

.fi
.PP
 
.PP
Definition at line 4 of file Cluster\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NEAT_PyGenetics from the source code\&.
