.TH "NEAT_PyGenetics.NEAT.Tests.MockClasses.mock_ClusterRepository.mock_ClusterRepository" 3 "Wed Apr 6 2016" "NEAT_PyGenetics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NEAT_PyGenetics.NEAT.Tests.MockClasses.mock_ClusterRepository.mock_ClusterRepository \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBreset\fP (self)"
.br
.ti -1c
.RI "def \fBget_cluster_count\fP (self)"
.br
.ti -1c
.RI "def \fBadd_cluster_with_representative\fP"
.br
.ti -1c
.RI "def \fBget_current_clusters\fP (self)"
.br
.ti -1c
.RI "def \fBget_cluster_by_representative\fP"
.br
.ti -1c
.RI "def \fBupdate_fitness_for_cluster\fP"
.br
.ti -1c
.RI "def \fBupdate_max_population_for_cluster\fP"
.br
.ti -1c
.RI "def \fBupdate_offspring_for_cluster\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBclusters\fP"
.br
.ti -1c
.RI "\fBnext_id\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file mock_ClusterRepository\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NEAT_PyGenetics from the source code\&.
