.TH "NEAT_PyGenetics.NEAT.Tests.NetworkingTests.CommandsTests.test_baseCommand.TestBaseCommand" 3 "Wed Apr 6 2016" "NEAT_PyGenetics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NEAT_PyGenetics.NEAT.Tests.NetworkingTests.CommandsTests.test_baseCommand.TestBaseCommand \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetUp\fP (self)"
.br
.ti -1c
.RI "def \fBtest_from_dict\fP (self)"
.br
.ti -1c
.RI "def \fBtest_as_dict\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbase_command\fP"
.br
.ti -1c
.RI "\fBdictionary\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file test_baseCommand\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NEAT_PyGenetics from the source code\&.
