.TH "NEAT_PyGenetics.NEAT.Tests.RepositoryTests.test_clusterRepository.TestClusterRepository" 3 "Wed Apr 6 2016" "NEAT_PyGenetics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NEAT_PyGenetics.NEAT.Tests.RepositoryTests.test_clusterRepository.TestClusterRepository \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetUp\fP (self)"
.br
.ti -1c
.RI "def \fBtest_get_current_clusters\fP (self)"
.br
.ti -1c
.RI "def \fBtest_add_cluster_with_representative\fP (self)"
.br
.ti -1c
.RI "def \fBtest_archive_cluster\fP (self)"
.br
.ti -1c
.RI "def \fBtest_get_cluster_by_representative\fP (self)"
.br
.ti -1c
.RI "def \fBtest_get_cluster_count\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdb\fP"
.br
.ti -1c
.RI "\fBcluster_repository\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 10 of file test_clusterRepository\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NEAT_PyGenetics from the source code\&.
