.TH "NEAT_PyGenetics.NEAT.Networking.Client.NEATClient.NEATClient" 3 "Wed Apr 6 2016" "NEAT_PyGenetics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NEAT_PyGenetics.NEAT.Networking.Client.NEATClient.NEATClient \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits object\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, server_address, server_port)"
.br
.ti -1c
.RI "def \fBrun_command\fP (self, command)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file NEATClient\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NEAT_PyGenetics from the source code\&.
