.TH "NEAT_PyGenetics.NEAT.Tests.AnalystTests.test_genomeSelector.test_genomeSelector" 3 "Wed Apr 6 2016" "NEAT_PyGenetics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NEAT_PyGenetics.NEAT.Tests.AnalystTests.test_genomeSelector.test_genomeSelector \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetUp\fP (self)"
.br
.ti -1c
.RI "def \fBtest_getGenomesInCluster\fP (self)"
.br
.ti -1c
.RI "def \fBtest_getClusterAreaSortedByFitness\fP (self)"
.br
.ti -1c
.RI "def \fBtest_selectGenomesForBreeding_and_selectGenomesForMutation\fP (self)"
.br
.ti -1c
.RI "def \fBtest_selectClusterForCombination\fP (self)"
.br
.ti -1c
.RI "def \fBtest_selectClusterCombination\fP (self)"
.br
.ti -1c
.RI "def \fBtest_selectGenomesForDiscarding\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmock_genome_repository\fP"
.br
.ti -1c
.RI "\fBmock_cluster_repository\fP"
.br
.ti -1c
.RI "\fBmock_selection_parameters\fP"
.br
.ti -1c
.RI "\fBgenome_selector\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file test_genomeSelector\&.py\&.
.SH "Member Function Documentation"
.PP 
.SS "def NEAT_PyGenetics\&.NEAT\&.Tests\&.AnalystTests\&.test_genomeSelector\&.test_genomeSelector\&.test_selectGenomesForDiscarding ( self)"

.PP
.nf
checks if 20% of worst cluster or genomes were selected
:return:

.fi
.PP
 
.PP
Definition at line 117 of file test_genomeSelector\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NEAT_PyGenetics from the source code\&.
