.TH "NEAT_PyGenetics.NEAT.Tests.NetworkingTests.CommandsTests.test_getBlockCommand.TestGetBlockCommand" 3 "Wed Apr 6 2016" "NEAT_PyGenetics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NEAT_PyGenetics.NEAT.Tests.NetworkingTests.CommandsTests.test_getBlockCommand.TestGetBlockCommand \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SH "Detailed Description"
.PP 
Definition at line 4 of file test_getBlockCommand\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NEAT_PyGenetics from the source code\&.
