.TH "NEAT_PyGenetics.NEAT.Networking.Server.JSONSocket.JSONSocket" 3 "Wed Apr 6 2016" "NEAT_PyGenetics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NEAT_PyGenetics.NEAT.Networking.Server.JSONSocket.JSONSocket \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Thread\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, server_address, server_port, header_size=16, chunk_size=1024)"
.br
.ti -1c
.RI "def \fBsocket_alive\fP (self)"
.br
.ti -1c
.RI "def \fBclose_connection\fP (self)"
.br
.ti -1c
.RI "def \fBsend_dict\fP"
.br
.ti -1c
.RI "def \fBreceive_dict\fP (self)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file JSONSocket\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NEAT_PyGenetics from the source code\&.
