.TH "NEAT_PyGenetics.NEAT.Tests.GenomeClustererTests.test_genomeClusterer.TestGenomeClusterer" 3 "Wed Apr 6 2016" "NEAT_PyGenetics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NEAT_PyGenetics.NEAT.Tests.GenomeClustererTests.test_genomeClusterer.TestGenomeClusterer \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetUp\fP (self)"
.br
.ti -1c
.RI "def \fBtest_cluster_genome_no_clusters\fP (self)"
.br
.ti -1c
.RI "def \fBtest_cluster_genome_no_delta_less\fP (self)"
.br
.ti -1c
.RI "def \fBtest_cluster_genome_with_delta_less\fP (self)"
.br
.ti -1c
.RI "def \fBtest_calculate_delta\fP (self)"
.br
.ti -1c
.RI "def \fBtest_calculate_disjoint_excess_count\fP (self)"
.br
.ti -1c
.RI "def \fBtest_calculate_w_bar\fP (self)"
.br
.ti -1c
.RI "def \fBtest_calculate_cluster_fitness\fP (self)"
.br
.ti -1c
.RI "def \fBtest_calculate_cluster_offspring_values\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBclustering_parameters\fP"
.br
.ti -1c
.RI "\fBdb_connector\fP"
.br
.ti -1c
.RI "\fBmock_genome_repository\fP"
.br
.ti -1c
.RI "\fBmock_cluster_repository\fP"
.br
.ti -1c
.RI "\fBgenome_clusterer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 15 of file test_genomeClusterer\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NEAT_PyGenetics from the source code\&.
