.TH "test_simulationClient.TestSimulationClient" 3 "Wed Apr 6 2016" "NEAT_PyGenetics" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_simulationClient.TestSimulationClient \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits TestCase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fBsetUp\fP (self)"
.br
.ti -1c
.RI "def \fBtest_announce_session_fail\fP (self)"
.br
.ti -1c
.RI "def \fBtest_announce_session\fP (self)"
.br
.ti -1c
.RI "def \fBtest_get_block_fail\fP (self)"
.br
.ti -1c
.RI "def \fBtest_get_block\fP (self)"
.br
.ti -1c
.RI "def \fBtest_set_block_inputs_fail\fP (self)"
.br
.ti -1c
.RI "def \fBtest_set_block_inputs\fP (self)"
.br
.ti -1c
.RI "def \fBtest_get_block_outputs_fail\fP (self)"
.br
.ti -1c
.RI "def \fBtest_get_block_outputs\fP (self)"
.br
.ti -1c
.RI "def \fBtest_set_fitness_values_fail\fP (self)"
.br
.ti -1c
.RI "def \fBtest_set_fitness_values\fP (self)"
.br
.ti -1c
.RI "def \fBtest_advance_generation_fail\fP (self)"
.br
.ti -1c
.RI "def \fBtest_advance_generation\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsimulation_client\fP"
.br
.ti -1c
.RI "\fBmock_client\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file test_simulationClient\&.py\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for NEAT_PyGenetics from the source code\&.
